# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

require 'os'
require 'fastlane_core/ui/ui'

fastlane_require 'dotenv'

UI = FastlaneCore::UI unless Fastlane.const_defined?("UI")

platform :android do

    # before_all do |lane|
    #     Dotenv.overload '../../.env'
    #     environment = lane_context[SharedValues::ENVIRONMENT]
    #     unless environment.nil?
    #         puts "Load .env file of #{environment}"
    #         Dotenv.overload '../../.env.' + environment
    #     end
    # end

    lane :deploy_app_center do |options|
        work = nil
        if options[:work] != nil
            work = options[:work]
        elsif ENV["work"] != nil
            work = ENV["work"]
        end
        apk_path = build(work: work)
        upload_app_center(path: apk_path)
    end

    private_lane :build do |options|
        ARGS = ""

        if options[:work] != nil
            ARGS = "#{ARGS} -work #{options[:work]}"
        end
        
        unity(
            build_target: "Android",
            extra_args: ARGS
        )

        "#{ENV["FL_UNITY_PROJECT_PATH"]}/Build/android/#{ENV["PRODUCT_NAME"]}.apk"
    end

    lane :upload_app_center do |options|
        appcenter_upload(
            api_token: ENV["APPCENTER_ANDROID_API_TOKEN"],
            file: options[:path],
            notify_testers: true,
            app_os: "Android",
            upload_build_only: true,
            app_name: ENV["APPCENTER_ANDROID_APP_NAME"],
            release_notes: "upload #{Date.today.strftime("%Y%m%d")}"
        )
    end

    ################
    # lane :aab_to_appcenter do |options|
    #     # bundletool(
    #     #   ks_path: options[:keystore_path],
    #     #   ks_password: options[:keystore_password],
    #     #   ks_key_alias: options[:keystore_alias],
    #     #   ks_key_alias_password: options[:keystore_alias_password],
    #     #   bundletool_version: '1.10.0',
    #     #   aab_path: options[:aab_path],
    #     #   apk_output_path: options[:apk_output_path],
    #     #   verbose: true
    #     # )
    #     bundletool(
    #         ks_path: "D:/workspace/unity/AppBuilder/secrets/deploy.keystore",
    #         ks_password: "000000",
    #         ks_key_alias: "deploy",
    #         ks_key_alias_password: "000000",
    #         bundletool_version: '1.10.0',
    #         aab_path: "D:/workspace/unity/AppBuilder/Build/Android/AppBuilder.aab",
    #         apk_output_path: "D:/workspace/unity/AppBuilder/Build/Android/AppBuilder.apk",
    #         verbose: true
    #     )
    # end
    #
    # lane :appcenter do |options|
    #     unless options[:path]
    #         raise 'require path'
    #     end
    #     appcenter_upload(
    #         api_token: ENV["APPCENTER_ANDROID_API_TOKEN"],
    #         file: options[:path],
    #         notify_testers: true,
    #         app_os: "Android",
    #         upload_build_only: true,
    #         app_name: "AppBuilder-Android",
    #         release_notes: "upload #{Date.today.strftime("%Y%m%d")}"
    #     )
    # end
 
    # lane :upload_internal do
    #
    #     UNITY_VERSION = "2021.2.12f1";
    #     UNITY_PATH = get_unity_path(UNITY_VERSION)
    #
    #     PROJECT_DIR = File.expand_path('../', Dir.pwd)
    #     METHOD = 'Samples.Deploy.UseCase.Build.Android'
    #     LOGFILE = "#{PROJECT_DIR}/Editor.log"
    #     #
    #     ARGS = "#{LOGFILE} -appsettings \"Assets/Samples/Deploy/UseCase\""
    #
    #     unity(
    #         unity_path: UNITY_PATH,
    #         # unity_version: UNITY_VERSION,
    #         project_path: PROJECT_DIR,
    #         build_target: "Android",
    #         execute_method: METHOD,
    #         extra_args: ARGS
    #     )
    #
    #     upload_to_play_store(
    #         track: "internal",
    #         aab: File.expand_path("../Build/Android/AppBuilder.aab", Dir.pwd),
    #         release_status: "draft"
    #     )
    # end
end

platform :ios do

    lane :deploy_device do |options|
        xcode_path = build(work: options[:work])
        destination = "platform=iOS,id=#{ENV["DEPLOY_DEVICE_ID"]}"

        install_device(
            product_name: ENV["PRODUCT_NAME"],
            project: xcode_path,
            team_id: ENV["TEAM_ID"],
            destination: destination,
            device: ENV["DEPLOY_DEVICE_ID"],
        )
    end

    lane :install_device do |options|
        product_name = options[:product_name]
        project = options[:project]
        team_id = options[:team_id]
        destination = options[:destination]
        device = options[:device]

        update_code_signing_settings(
            path: project,
            targets: "Unity-iPhone",
            use_automatic_signing: true,
            team_id: team_id
        )

        begin

            scan(
                project: project,
                scheme: 'Unity-iPhone',
                destination: destination,
                build_for_testing: true
            )

            derived_path = lane_context[SharedValues::SCAN_DERIVED_DATA_PATH]

            sh "(ios-deploy -i #{device} -b #{derived_path}/Build/Products/Debug-iphoneos/#{product_name}.app || true)"
        rescue => ex
            UI.error(ex)
        end
    end

    error do |lane, exception|

    end

    lane :signing_xcode_development do |options|
        
        xcode_path = options[:xcode_path]

        match(type: "development", readonly: true)
        profiles = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
        update_signing(profiles: profiles, path: xcode_path, code_sign_identity: "Apple Development", build_configurations: "ReleaseForRunning")
    end
    
    lane :signing_xcode_distribution do |options|
        xcode_path = options[:xcode_path]

        match(type: "appstore", readonly: true)
        profiles = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
        update_signing(profiles: profiles, path: xcode_path, code_sign_identity: "Apple Distribution", build_configurations: "Release")
    end
    
    lane :deploy_app_center do |options|

        xcode_root = options[:xcode_root]
        xcode_proj = "#{xcode_root}/Unity-iPhone.xcodeproj"
        
        project_path = xcode_proj

        xcode_workspace = options[:xcode_workspace]
        if xcode_workspace != nil
            project_path = "#{xcode_root}/#{xcode_workspace}"
        end
        
        puts xcode_root
        puts xcode_proj
        puts project_path

        #if options[:work] != nil
        #    xcode_path = build(work: options[:work])
        #end
        #elsif options[:xcode_path] != nil
        #    xcode_path = options[:xcode_path]
        #end

        match(type: "development", readonly: true)
        profiles = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
        update_signing(profiles: profiles, path: xcode_proj, code_sign_identity: "Apple Development", build_configurations: ["ReleaseForRunning"])
        
        ipa_path, dsym_path = export_ipa(project_path: project_path, output_dir: "Build/iOS", export_method: "development", configuration: "ReleaseForRunning")

        upload_app_center(path: ipa_path)
    end

    private_lane :build do |options|
        ARGS = ""

        if options[:work] != nil
            ARGS = "#{ARGS} -work #{options[:work]}"
        end

        unity(
            build_target: "iOS",
            extra_args: ARGS
        )

        "#{ENV["FL_UNITY_PROJECT_PATH"]}/Build/ios/#{ENV["PRODUCT_NAME"]}/Unity-iPhone.xcodeproj"
    end

    private_lane :export_ipa do |options|
        project_path = options[:project_path]
        workspace_path = nil
        
        if project_path.end_with?(".xcworkspace")
            workspace_path = project_path;
            project_path = nil
        end
        
        export_method = options[:export_method]

        output_dir = "#{options[:output_dir]}/#{export_method}"

        archive_path = "#{output_dir}/Archive"
        
        configuration = options[:configuration]
        
        puts "+++ fastlane gym"
        gym(
            scheme: "Unity-iPhone",
            project: project_path,
            workspace: workspace_path,
            configuration: configuration,
            clean: true,
            output_directory: output_dir,
            export_method: export_method,
            include_bitcode: false,
            export_options: {
                compileBitcode: false
            },
            archive_path: archive_path
        )
        archive_path = File.expand_path("../#{archive_path}.xcarchive", Dir.pwd)
        if File.exist?(archive_path)
            sh(command: "rm -vfr #{archive_path}")
        end
        puts "--- fastlane gym"
        
        # product_name = ENV["PRODUCT_NAME"]
        # ipa_path = File.expand_path("/#{output_dir}/#{product_name}.ipa", Dir.pwd)
        # dsym_path = File.expand_path("/#{output_dir}/#{product_name}.app.dSYM.zip", Dir.pwd)
        #
        ipa_path = lane_context[:IPA_OUTPUT_PATH]
        dsym_path = lane_context[:DSYM_OUTPUT_PATH]
        
        puts "ipa: #{ipa_path}"
        puts "dsym: #{dsym_path}"
        
        [ipa_path, dsym_path]
    end

    private_lane :update_signing do |options|
        profiles = options[:profiles]
        path = options[:path]
        code_sign_identity = options[:code_sign_identity]
        build_configurations = options[:build_configurations]

        update_code_signing_settings(
            path: path,
            targets: "Unity-iPhone",
            use_automatic_signing: false,
            team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
            profile_name: profiles[CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)],
            code_sign_identity: code_sign_identity,
            build_configurations: build_configurations
        )
    end

    private_lane :upload_app_center do |options|

        build_only = options[:dsym].nil? ? true : false
        dsym_path = options[:dsym]
        notify_testers = options[:notify].nil? ? true : options[:notify]

        appcenter_upload(
            api_token: ENV["APPCENTER_IOS_API_TOKEN"],
            file: options[:path],
            notify_testers: notify_testers,
            app_os: "iOS",
            upload_build_only: build_only,
            dsym: dsym_path,
            app_name: ENV["APPCENTER_IOS_APP_NAME"],
            release_notes: "upload #{Date.today.strftime("%Y%m%d")}"
        )
    end

    lane :deploy_testflight do |options|
        
        xcode_root = options[:xcode_root]
        xcode_proj = "#{xcode_root}/Unity-iPhone.xcodeproj"
        
        project_path = xcode_proj

        xcode_workspace = options[:xcode_workspace]
        if xcode_workspace != nil
            project_path = "#{xcode_root}/#{xcode_workspace}"
        end
        
        puts xcode_root
        puts xcode_proj
        puts project_path

        unless xcode_proj
            UI.user_error!("empty xcode_proj")
        end
        
        version_number = ENV["XCODE_PROJECT_VERSION"]
        unless version_number.nil? || version_number.strip.empty?
            increment_version_number(
                version_number: version_number,
                xcodeproj: xcode_proj
            )                
        end

        match(type: "appstore", readonly: true)
        profiles = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
        update_signing(profiles: profiles, path: xcode_proj, code_sign_identity: "Apple Distribution", build_configurations: ["Release"])
        
        ipa_path, dsym_path = export_ipa(project_path: project_path, output_dir: "Build/AppStore", export_method: "app-store", configuration: "Release")
        
        upload_pilot(ipa_path: ipa_path)
    end

    lane :upload_pilot do |options|
        
        puts "--- upload testflight"
        
        # ipa_path = File.expand_path("../Build/AppStore/AppBuilder.ipa");
        ipa_path = options[:ipa_path]
        api_key_path = ENV["APP_STORE_CONNECT_API_KEY_PATH"]
        
        latest_testflight_build_number(initial_build_number: 0)
        
        build_number = lane_context[SharedValues::LATEST_TESTFLIGHT_BUILD_NUMBER]
        #version = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]
        pilot(
#             version: version,
            skip_waiting_for_build_processing: true,
            skip_submission: true,
            build_number: build_number + 1,
            api_key_path: api_key_path,
            # username: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id),
            ipa: ipa_path,
        )
    end

    # lane :adhoc do
    #     match(
    #         type: "adhoc",
    #         readonly: false,
    #         force_for_new_devices: true
    #     )
    #     profiles = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    #     update_code_signing_settings(
    #         path: XCODE_PROJECT,
    #         targets: "Unity-iPhone",
    #         use_automatic_signing: false,
    #         team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
    #         profile_name: profiles[CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)],
    #         code_sign_identity: "Apple Distribution",
    #     # build_configurations: ["Debug", "Release", "ReleaseForProfiling", "ReleaseForRunning"]
    #     )
    #     gym(
    #         scheme: "Unity-iPhone",
    #         project: XCODE_PROJECT,
    #         configuration: "Release",
    #         clean: true,
    #         output_directory: "Build/AdHoc",
    #         export_method: "ad-hoc",
    #         include_bitcode: false,
    #         export_options: {
    #             compileBitcode: false
    #         },
    #         archive_path: "Build/iOS/Archive"
    #     )
    #     # install_on_device(
    #     #     device_id: "00008101-0005485C3E31003A",
    #     #     ipa: lane_context["IPA_OUTPUT_PATH"] #lane_context["IPA_OUTPUT_PATH"]
    #     # )
    # end
    #
    # lane :adhoc_app_center do
    #     match(
    #         type: "adhoc",
    #         readonly: false,
    #         force_for_new_devices: true
    #     )
    #     profiles = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    #     update_code_signing_settings(
    #         path: XCODE_PROJECT,
    #         targets: "Unity-iPhone",
    #         use_automatic_signing: false,
    #         team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
    #         profile_name: profiles[CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)],
    #         code_sign_identity: "Apple Distribution",
    #     )
    #     gym(
    #         scheme: "Unity-iPhone",
    #         project: XCODE_PROJECT,
    #         configuration: "Release",
    #         clean: true,
    #         output_directory: "Build/AdHoc",
    #         export_method: "ad-hoc",
    #         include_bitcode: false,
    #         export_options: {
    #             compileBitcode: false
    #         },
    #         archive_path: "Build/iOS/Archive"
    #     )
    #     archive_path = File.expand_path("../Build/iOS/Archive.xcarchive", Dir.pwd);
    #     if File.exist?(archive_path)
    #         File.chmod(666, archive_path)
    #         File.delete(archive_path)
    #     end
    #
    #     appcenter_upload(
    #         # api_token: ENV["APP_CENTER_API_TOKEN"], # APPCENTER_API_TOKEN
    #         # owner_name: "qkrsogusl3", # APPCENTER_OWNER_NAME
    #         # owner_type:"user",
    #         # app_name: "AppBuilder", # APPCENTER_APP_NAME
    #         file: lane_context["IPA_OUTPUT_PATH"],
    #         notify_testers: true,
    #         app_os: "iOS",
    #         upload_build_only: true,
    #         release_notes: "upload #{Date.today.strftime("%Y%m%d")}"
    #     )
    # end

    # lane :build_ipa do
    #     project = File.expand_path("../Build/iOS/AppBuilder/Unity-iPhone.xcodeproj", Dir.pwd)
    #
    #     identifier = "com.DefaultCompany.AppBuilder"
    #     automatic_code_signing(
    #         path: project,
    #         use_automatic_signing: true,
    #         team_id: "D755A5HZ37",
    #         bundle_identifier: identifier,
    #         profile_uuid: "YR9GNYKWY2"
    #     # code_sign_identity: "Apple Development",
    #     # profile_name: "iOS Team Provisioning Profile: #{identifier}"
    #     )
    #
    #     build_ios_app(
    #         project: project,
    #         scheme: "Unity-iPhone",
    #         output_directory: File.expand_path("../Build/iOS", Dir.pwd),
    #         # output_name: "App"
    #         # codesigning_identity:"Apple Development: SEONGHO PARK",
    #         skip_codesigning: true
    #     )
    # end
end
